USE [master]
GO

/****** Object:  Database [ClietBankStat]    Script Date: 29.10.2015 22:57:40 ******/
CREATE DATABASE [ClietBankStat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClietBankStat', FILENAME = N'D:\SQLServerDB\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClietBankStat.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClietBankStat_log', FILENAME = N'D:\SQLServerDB\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClietBankStat_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ClietBankStat] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClietBankStat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClietBankStat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClietBankStat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClietBankStat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClietBankStat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClietBankStat] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClietBankStat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClietBankStat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClietBankStat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClietBankStat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClietBankStat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClietBankStat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClietBankStat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClietBankStat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClietBankStat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClietBankStat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClietBankStat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClietBankStat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClietBankStat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClietBankStat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClietBankStat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClietBankStat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClietBankStat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClietBankStat] SET RECOVERY FULL 
GO

ALTER DATABASE [ClietBankStat] SET  MULTI_USER 
GO

ALTER DATABASE [ClietBankStat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClietBankStat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClietBankStat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClietBankStat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ClietBankStat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClietBankStat] SET  READ_WRITE 
GO


